name: Validate

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  hacs:
    name: HACS validatie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest validatie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
